name: ✨ Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          options: "-l 88 -t py311 --extend-exclude 'other'"
          src: "."
          jupyter: false